# Thanks to https://www.youtube.com/watch?v=YlVmVO0zAfw for some tips

FROM node:16-alpine as builder

# production image
ENV NODE_ENV=production

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --production

USER node
COPY sendgrid.js ./

#multi build stage to save space
FROM node:16-alpine

USER node
COPY --from=builder /usr/src/app /app
WORKDIR /app

# expose port and start server
EXPOSE 5001
CMD ["node","sendgrid.js"]